services:
  app:
    image: node:latest
    user: "${UID}:${GID}"
    working_dir: /app
    network_mode: host
    volumes:
      - ./src:/app
    command: sh -c "npm run dev -- --host --port 40638"
    environment:
      - NODE_ENV=development
